server:
  jwt-secret: ozline
  version: "1.0"
  name: todolist

snowflake:
  worker-id: 0
  datancenter-id: 0

services:
  api:
    name: api
    addr:
      - 127.0.0.1:10001
  user:
    name: user
    addr:
      - 127.0.0.1:10002
  task:
    name: task
    addr:
      - 127.0.0.1:10003
  experimental:
    name: experimental
    addr:
      - 127.0.0.1:10004
      - 127.0.0.1:10005
      - 127.0.0.1:10006
      - 127.0.0.1:10007
      - 127.0.0.1:10008

mysql:
  addr: 127.0.0.1:3306
  database: todolist
  username: todolist
  password: todolist
  charset: utf8mb4

etcd:
  addr: 127.0.0.1:2379